### PR TITLE
added error message on render if window.grecaptcha failed to load

### PR DESCRIPTION
**Pull request by Hidejec**
I was having a problem if the grecaptcha failed to load. See image below.

image

It's kind of hard to replicate and it only happens to me sometimes. It's because the window.grecaptcha failed to load directly from google. I've added an error message in the render function since it's the one that causing the error.

### CODE REVIEW

**Comment by DanSnow** [comment]
If this will really happen, it should be report to the user.
But using `alert` it not a good idea.
Since it will popup a window directly.

**Comment by DanSnow** [comment]
@Hidejec what is the version of vue-recaptcha that you are using?

**Comment by Hidejec** [comment]
Ahhh I see, I guess throwing an Error Exception like the one in your assertLoaded function will do?

I'm using v1.1.0

**Comment by DanSnow** [comment]
I think this has already fixed in v1.1.1. Can you please upgrade and try it?

**Pull request closed without merging**
